### ISSUE TITLE
Can I help develop this?

### ISSUE THREAD

**Issue by Jpac14** [AppleFlavored/jasm#1]
Hi,

I was having the exact same idea. I was going to start developing it today. But before I did I searched for something that might be out there and found this. I was wonder if I would be able to help make this with you.

I am very new to rust and this would be a learning experience for me. But I have lot's of experience in other languages like C.

If your interested, we can find a way to get in contact.

**Comment by AppleFlavored** [comment]
Hey, Jpac14!

Sorry for the late response. Honestly, I wasn't expecting for this repo to be seen so quickly.

I’m not sure if I'm ready for additional help just yet as this was intended as a personal project.

However, I will be willing to accept contributions whenever I get started. 😀

Thanks for your interest!
